version: "3.8"
services:
  ikfrontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  ikbackend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
